site_name: Wombat Auto Rig
repo_url: https://github.com/ThomasEscalle/WombatAutoRig
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode    
      primary: black
      accent: lime
    - scheme: light
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: teal
      accent: purple 
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/james-willett
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/TheJamesWillett
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/willettjames/

nav:
  - Home: index.md
  - Getting Started: 01_GettingStarted.md
  - Tools: 02_Tools.md
  - Python API: 03_PythonAPI.md
  - FAQ: 04_FAQ.md
  - About: 05_About.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg